server:
  servlet:
    context-path: "/api"
  port: 9286 # alphanumeric transformation C -> 2, U -> 8, N -> 6, CUN -> 286, 9CUN -> 9286
# ----------------------------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: ms_custodial_network
  data:
    mongodb:
      uri: ${MONGODB_URI}
# ----------------------------------------------------------------------------------------------------------------------------------
jwt:
  secret-key: "4eded600-1ff4-4a8a-8461-9a91ad8dc644"
  validity-in-ms: 7200000
# ----------------------------------------------------------------------------------------------------------------------------------
cross-mint:
  api-key: ${CROSS_MINT_API_KEY}
  app-identifier: "darto@darto.com"
  app-collection: ""
# ----------------------------------------------------------------------------------------------------------------------------------
feign-client:
  cross-mint:
    url: "https://staging.crossmint.com/api"
    name: "crossMintClientService"